# Generated by Django 2.2.1 on 2019-06-03 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20190531_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='files/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='residents/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='religion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='birthplace',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
