# Generated by Django 2.2.1 on 2019-06-03 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20190603_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='file_upload',
            field=models.FileField(blank=True, upload_to='media/%Y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='photo_main',
            field=models.ImageField(blank=True, upload_to='media/%Y/%m/%d'),
        ),
    ]
