# Generated by Django 2.2.2 on 2019-06-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20190603_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='house_num',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='street',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='zone',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
