# Generated by Django 2.2.1 on 2019-05-20 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('officials', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='official',
            name='is_mvp',
            field=models.BooleanField(default=False),
        ),
    ]
